#! /usr/bin/env bash
set -e

# dependencies
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y curl wget git apt-transport-https \
                   sudo vim zlib1g-dev supervisor psmisc \
                   jq netcat # Parsing stellar-core JSON for standalone network and checking core HTTP server
apt-get clean

echo "\nDone installing dependencies...\n"
