#! /usr/bin/env bash
set -e

export DEBIAN_FRONTEND=noninteractive

# install stellar-core from https://github.com/stellar/stellar-core/blob/master/INSTALL.md#basic-installation
wget -q -O https://github.com/stellar/stellar-core/archive/refs/tags/v${STELLAR_CORE_VERSION}.tar.gz | tar xz &
cd stellar-core
./autogen.sh
./configure
make
make check
make install


# apt-get -y install gnupg1 rsync wget
# wget -qO - https://apt.stellar.org/SDF.asc | apt-key add -
# echo "deb https://apt.stellar.org focal stable" >/etc/apt/sources.list.d/SDF.list
# echo "deb https://apt.stellar.org focal unstable" >/etc/apt/sources.list.d/SDF-unstable.list
# apt-get update
# apt-get install -y stellar-core=${STELLAR_CORE_VERSION}
# apt-get install -y stellar-horizon=${HORIZON_VERSION}
# apt-get clean
# echo "\nDone installing stellar-core and horizon...\n"
